name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master
  schedule:
    # We want to run right after the `latest` image is published.
    # So, let's do it an hour right after. Look the schedule of publishing here:
    # https://github.com/alexhumphreys/idris2-dockerfile/blob/main/.github/workflows/docker-image.yml
    - cron: '0 1 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with pack latest
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build lib
        run: pack install tutorial
